name: Gradient
main: io.github.karlatemp.gradient.GradientBukkit
version: "1.0"
author: Karlatemp


permissions:
  "gradient.command":
     default: op

commands:
  gradient:
    permission: gradient.command
